version: '3.4'

services:
  dockerizedapp:
    image: dockerizedapp
    build:
      context: dockerized-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
